[package]
name = "memory_map"
version = "0.1.0"
authors = ["Benjamin Strauch <b.strauch@fu-berlin.de>"]

[dependencies]
bitflags = "1.0.3"
byteorder = "1.2.3"
gtk = "0.5.0"
gio = "0.5.0"
glib = "0.6.0"

[features]
default = ["gtk/v3_10"] # in case your version is 3.10